### ISSUE TITLE
Excuse me,how do I train my dataset

### ISSUE THREAD

**Issue by mohenghui** [endo-yuki-t/UserControllableLT#1]

**Comment by endo-yuki-t** [comment]
Thank you for your interest in our work. You need first to train StyleGAN2 on your dataset using rosinality's code: 
https://github.com/rosinality/stylegan2-pytorch
Then, please run our train.py with specifying the converted weights as follows.  
python scripts/train.py --exp_dir=results --stylegan_weights=[your converted weights path]
You can also use weights trained with the official StyleGAN2 code by converting them using convert_weight.py provided by rosinality.
